// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// R_ssc_version
int R_ssc_version();
RcppExport SEXP _RSSC_R_ssc_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(R_ssc_version());
    return rcpp_result_gen;
END_RCPP
}
// R_ssc_build_info
std::string R_ssc_build_info();
RcppExport SEXP _RSSC_R_ssc_build_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(R_ssc_build_info());
    return rcpp_result_gen;
END_RCPP
}
// R_ssc_module_create
int R_ssc_module_create(std::string x);
RcppExport SEXP _RSSC_R_ssc_module_create(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(R_ssc_module_create(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSSC_R_ssc_version", (DL_FUNC) &_RSSC_R_ssc_version, 0},
    {"_RSSC_R_ssc_build_info", (DL_FUNC) &_RSSC_R_ssc_build_info, 0},
    {"_RSSC_R_ssc_module_create", (DL_FUNC) &_RSSC_R_ssc_module_create, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSSC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
