# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
dataiotest <- function(x) {
    .Call('_RSSC_dataiotest', PACKAGE = 'RSSC', x)
}

#'@export
pvwattstest <- function(filename) {
    .Call('_RSSC_pvwattstest', PACKAGE = 'RSSC', filename)
}

#'@export
R_ssc_version <- function() {
    .Call('_RSSC_R_ssc_version', PACKAGE = 'RSSC')
}

#'@export
R_ssc_build_info <- function() {
    .Call('_RSSC_R_ssc_build_info', PACKAGE = 'RSSC')
}

