# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
dataiotest_num <- function(x) {
    .Call('_RSSC_dataiotest_num', PACKAGE = 'RSSC', x)
}

#'@export
dataiotest_char <- function(x) {
    .Call('_RSSC_dataiotest_char', PACKAGE = 'RSSC', x)
}

#'@export
dataiotest_log <- function(x) {
    .Call('_RSSC_dataiotest_log', PACKAGE = 'RSSC', x)
}

#'@export
R_ssc_version <- function() {
    .Call('_RSSC_R_ssc_version', PACKAGE = 'RSSC')
}

#'@export
R_ssc_build_info <- function() {
    .Call('_RSSC_R_ssc_build_info', PACKAGE = 'RSSC')
}

